######################################################################
# Automatically generated by qmake (2.01a) Tue May 26 20:39:14 2015
######################################################################

TEMPLATE = app
TARGET = display
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11 -I/usr/include/python2.7
QMAKE_LFLAGS += -lpython2.7
QT += core webkit

# Input
SOURCES += main.cpp
HEADERS += main.h
